### ISSUE TITLE
Considering making existsFolder() and existsFile() public

### ISSUE THREAD

**Issue by mql21** [donbalon4/API_Alfresco#7]
I know that these two methods are written for internal use, but API_Alfresco users might want to check themselves if a given folder or file already exists to do what they need. 

For example, I just needed to check if a given folder existed. If so, I'd move a file into it. If it didn't exist then I'd move that file into another folder that will always exist.

As far as I know, if a given file or folder already exists, an Exception will be thrown. It might be a right way to go for programmers but end users could freak out when watching that exception. 

So, if existsFolder() and existsFile() were public, then it could be programmers themselves who could handle files or folders that already exist to then show the proper message to the end user.

However I could be missing some other way to handle this whole thing without the need of these two methods, so any information will be welcome.

Thanks in advance.

**Comment by donbalon4** [comment]
Hi @miquelp , it's a geat idea. Thanks for collaborate!

**Comment by mql21** [comment]
Hi @donbalon4! I just created a pull request with proper changes done (now existsFolder() and FileExists() functions are public). I made some testing on it and it's been successful. Now programmers should be able to use those functions from their external PHP code with success. 

Check it out and let me know if there's need of any further changes! 

Thanks.

**Comment by donbalon4** [comment]
Everything is OK. Thank you! :)
