### ISSUE TITLE
Exception being thrown when creating folders or files with special characters

### ISSUE THREAD

**Issue by mql21** [donbalon4/API_Alfresco#9]
I've been using your library these past days and it works pretty well. 

Anyway, I've noticed a few bugs when **creating folders or files containing special characters** (including blank spaces). If you try to create a folder or a file with special characters on its name, then a *CmisConstraintException* will be thrown. 

This is happening because **setFolderByPath(name)** makes an HTTPrequest (inside method **doRequest()**). So if folder/file name contains special characters, then the HTTP link won't be build properly and the HTTP request will fail. In example, if your folder name contains a blank space, when calling **doRequest();** that blank space will split the URL in two, so request will fail. Same with any kind of special character.

It's pretty normal that users will create folders with blank spaces, so it should be handled in your library. So far, when trying to create a folder with blank spaces (or special chars), programmers are the ones who have to handle it by doing something like:

```
$myFolder = "My Folder"; //some folder name
$myFolder = str_replace(' ', '%20', $myFolder); //"%20" is a valid blank space for HTTP requests
$conexion->setFolderByPath($myFolder); //would fail without the previous line, but with %20 will work
$conexion->createFolder("blablabla"); //do some operation
```

Anyway, it shouldn't be programmers who have to handle this kind of stuff. Your library should indeed check this kind of things so programmers don't have to worry about it and can easily **setFolderByPath("Folder With Blank Spaces");** or **createFolder("Folder With Blank Spaces");** 

I've been taking a look to the code and realized that there's an interesting method called **_extractEspecialChars();_** but it's not being called inside **createFolder();** nor in **setFolderByPath()**. Not only these two methods should be also extracting special chars, but also library should allow programmers to create folders or files with blanket spaces with no need of extracting them. Indeed, as I'm doing in my PHP code, your library should be replacing blank spaces with a "%20" symbol, so HTTP requests don't fail with blanket spaces. And then, once the HTTP request is done, you should be replacing "%20" back to blanket spaces.

I can work on it if you want, I'll let you know when I fix it and get it to work.

**Comment by donbalon4** [comment]
hey @miquelp. yes, please fix this. I appreciate very much your gently help :)

**Comment by mql21** [comment]
Hi @donbalon! I'm working on it now and it's pretty much fixed. However I need to have some points cleared before starting a pull request.

For example, if I want to create a folder named _"MyFolder_" inside _"/Sites/MySite/ParentFolder"_, I guess the right way to go could be (at least it works):

```
$basePath = "/Sites/MySite/ParentFolder";
$folderName = "MyFolder";
$conexion->setFolderByPath($basePath);
$conexion->createFolder($folderName);
```
Am I right? Or is there any other way to do this?

Problem here is that in **_setFolderByPath()_** I need to call **_extractSpecialChars()_** but this method also extracts symbol "/". So  **_"/Sites/MySite/ParentFolder"_** will end up being **_"SitesMySiteParentFolder"_**, which is not the correct path. So far I've fixed this by preventing _extractSpecialChars()_ from extracting "/" symbol. So now "/" symbols are allowed. But this way, of course, if ```$folderName``` contains a "/" then it'll fail since slashes won't be extracted from the name, and the path will be messed up.

If I don't extract "/" it works, but then with wrong names with "/" it will fail. Any idea? 

Thanks!

**Comment by mql21** [comment]
Also, other than the "/" issue (should be fixed in future commits), everything else is fixed. Now special chars and blank spaces are handled within the library so programmers don't need to take care of it. I can start a pull request if you want!

Thanks!

P.S: Made some testing and it works fine when creating a folder named "ñññññññññ Éaê-e ñósfïs". Indeed it will create a folder named "nnnnnnnnn Eaee nosfis" in Alfresco. As you see, special chars are extracted but blank spaces remain in the name and don't cause any problem anymore.

**Comment by donbalon4** [comment]
Thank you so much @miquelp.
I think that by the moment we can treat $folderName variable inspecting if it contains a "/" character and remove it. After doing this we can call the _extractSpecialChar_ method

**Comment by mql21** [comment]
Yep, I thought about it.

If $folderName is an invalid folder name containing a "/" (i.e. "MyFol/der") then extracting "/" symbol would correct that name and it would work. But if parameter $folderName is something such as "/Sites/MySite/SomePath", then extracting "/" characters would mess it up and we'd end up having "SitesMySiteSomePath", which is not the right folder path so it would fail. Problem is how do we differentiate folder path separators ("/") with wrong "/" in a name. Right now it is all up to programmers not to use "/" within the name of a folder. If programmer takes care of it it'll work. However I think it should be also fixed so it is the libary who extracts only wrong "/" but keeps "/" folder separators in paths.
I'll take a look to it on monday (weekend don't have access to servers with Alfresco) and will let you know of any further fixes.

Thanks!

**Comment by donbalon4** [comment]
ohh, I see. Thank you!
